ICON := "images/icon.svg"

icons:
	rsvg-convert -h 16 ${ICON} > static/icon16.png
	rsvg-convert -h 19 ${ICON} > static/icon19.png
	rsvg-convert -h 32 ${ICON} > static/icon32.png
	rsvg-convert -h 48 ${ICON} > static/icon48.png
	rsvg-convert -h 128 ${ICON} > static/icon128.png

.PHONY: icons
